#!/bin/sh

## clear the logs (quietly)
rm -f intermine.log

## echo a big marker so we can see when this run started in the scroll
echo "##################################################################################################"
echo "###################################### integrate #################################################"
echo "##################################################################################################"

# ## ontologies
# ./gradlew integrate -Psource=so --stacktrace
# ./gradlew integrate -Psource=go --stacktrace
# ./gradlew integrate -Psource=to --stacktrace
# ./gradlew integrate -Psource=po --stacktrace

# ## LIS chado
# ./gradlew integrate -Psource=knowpulse-genomics --stacktrace
# ./gradlew integrate -Psource=knowpulse-proteins --stacktrace
# ./gradlew integrate -Psource=knowpulse-genetics --stacktrace
# ./gradlew integrate -Psource=knowpulse-featureprop --stacktrace
# ./gradlew integrate -Psource=knowpulse-genefamilies --stacktrace
# ./gradlew integrate -Psource=knowpulse-reactome-file --stacktrace

# ## ---------------------------------------------------------------------------------------------------------
# ## - ALL of the chado loaders must be DONE before continuing, because identifiers are changed by SQL below -
# ## ---------------------------------------------------------------------------------------------------------

# ## SQL updates
# ./gradlew generateUpdateTriggers
# psql lentilmine-dev -f dbmodel/build/resources/main/add-update-triggers.sql
# psql lentilmine-dev -f ../legfed-intermine-sql/cleanup-chado-bugs.sql
# psql lentilmine-dev -f ../legfed-intermine-sql/update-identifiers.sql
# psql lentilmine-dev -f ../legfed-intermine-sql/update-organism-genus-species.sql
# psql lentilmine-dev -f ../legfed-intermine-sql/update-organism-descriptions.sql
# psql lentilmine-dev -f ../legfed-intermine-sql/update-strain-descriptions.sql
# psql lentilmine-dev -f dbmodel/build/resources/main/remove-update-triggers.sql

# ## file sources
# ./gradlew integrate -Psource=lentil-qtl-ontology --stacktrace
# ./gradlew integrate -Psource=lentil-expression --stacktrace
