#!/bin/sh
NC='\033[0m'
LP='\033[1;35m'
echo -e "#################################################################"
echo -e "########################### ${LP}INTEGRATE${NC} ##########################"
echo -e "#################################################################"

./gradlew integrate --stacktrace -Psource=Lens-culinaris-description
./gradlew integrate --stacktrace -Psource=Lens-ervoides-description

#./gradlew integrate --stacktrace -Psource=CDC_Redberry.gnm2.7C5P
#./gradlew integrate --stacktrace -Psource=IG_72815.gnm1.ZDWF

./gradlew integrate --stacktrace -Psource=CDC_Redberry.gnm2.ann1.5FB4
./gradlew integrate --stacktrace -Psource=IG_72815.gnm1.ann1.R90F

./gradlew integrate --stacktrace -Psource=legume.genefam.fam1.M65K
./gradlew integrate --stacktrace -Psource=legume.genefam.fam1.M65K.trees_ML_rooted
./gradlew integrate --stacktrace -Psource=interpro
./gradlew integrate --stacktrace -Psource=interpro-go
./gradlew integrate --stacktrace -Psource=pfam-term
./gradlew integrate --stacktrace -Psource=panther-term
./gradlew integrate --stacktrace -Psource=go
./gradlew integrate --stacktrace -Psource=so
