#!/bin/sh

## clear the logs (quietly)
rm -f intermine.log

## echo a big marker so we can see when this run started in the scroll
echo "##################################################################################################"
echo "###################################### integrate #################################################"
echo "##################################################################################################"

## ontologies
./gradlew integrate -Psource=so --stacktrace
./gradlew integrate -Psource=go --stacktrace
./gradlew integrate -Psource=to --stacktrace
./gradlew integrate -Psource=po --stacktrace

